In [2]:
print("hello!")

hello!


# Библиотека NumPy
- Массивы

In [6]:
import numpy as np

In [7]:
list_1 = [10, 20, 30, 40]
arr_1 = np.array(list_1)

# print(arr_1)
# print(type(arr_1))

arr_1
type(arr_1)

numpy.ndarray

In [11]:
# Задача 1

a = [1,2,3,4]
b = [10,20,30,40]

# c = []
# for i in range(4):
#     c.append(a[i] * b[i])

c = []
for idx, item in enumerate(a):
    c.append(item * b[idx])
    
c 


[10, 40, 90, 160]

In [12]:
a = np.array(a)
b = np.array(b)

a, b

(array([1, 2, 3, 4]), array([10, 20, 30, 40]))

In [15]:
a * b

array([ 10,  40,  90, 160])

In [16]:
[10, 'a', 3,14, True]

[10, 'a', 3, 14, True]

In [17]:
np.array([10, 'a', 3,14, True])

array(['10', 'a', '3', '14', 'True'], dtype='<U11')

In [18]:
arr_2 = np.array([1,2,3])
arr_2[2] = 6.14
arr_2

array([1, 2, 6])

## Вектора
- 1-мерные массивы

In [19]:
# Вектор-строка
arr_3 = np.array([10,20,30,40,50])
arr_3

array([10, 20, 30, 40, 50])

## Матрица
- 2-мерные массивы

In [21]:
list_2 = [[1,2,3,4], [5,6,7,8]]
list_2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [23]:
# Матрица
arr_4 = np.array(list_2)
arr_4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
# Вектор-столбец
arr_5 = np.array([[10],[20],[30]])
arr_5

array([[10],
       [20],
       [30]])

In [25]:
# Вектор умножаем на скаляр
arr_6 = np.array([10,20,30,40,50])

arr_6 + 3

array([13, 23, 33, 43, 53])

## Функции генерации массивов

In [26]:
# создание одномерного массива из нулей
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [27]:
# создание двумерного массива из нулей
z = np.zeros((2, 5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
# создание трехмерного массива из нулей (тензор 3 ранга)
z = np.zeros ((2, 5, 4))
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [37]:
# создание одномерного массива из единиц 
y = np.ones (5)
y

array([1., 1., 1., 1., 1.])

In [38]:
y.dtype

dtype('float64')

In [39]:
# изменение типа данных
y.astype("int32")

array([1, 1, 1, 1, 1])

In [41]:
# измение формы
arr_7 = np.array(range(9))
arr_7

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
# атрибут, хранящий форму массива
arr_7.shape

(9,)

In [43]:
# метод, меняющий формуэ
# вектор-столбец
arr_7.reshape(9, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [44]:
# матрица 3*3
arr_7.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])