In [5]:
import numpy as np

In [4]:
# 1-мерный массив формой (длиной) 5
# со случайными значениями из равномерного распределения
# в диапазоне от 0 до 1
arr_1 = np.random.random(5)
arr_1

array([0.35341822, 0.71583512, 0.63111524, 0.67887815, 0.04488107])

In [5]:
arr_1.dtype

dtype('float64')

In [7]:
arr_1.astype("float16")

array([0.3535, 0.716 , 0.6313, 0.6787, 0.0449], dtype=float16)

In [6]:
# 2-мерный массив
np.random.random((3,5))

array([[0.64919545, 0.04657684, 0.29396647, 0.71689388, 0.25847956],
       [0.00516922, 0.48306246, 0.83459807, 0.0444834 , 0.60106678],
       [0.05399418, 0.59525855, 0.40701532, 0.18224397, 0.14433948]])

In [8]:
# Генерация массива с случайными целочисленными значениями
# если без формы, то это будет одно значение (скаляр)
# np.random.randint(0, 10)
np.random.randint(10)

5

In [10]:
# 1-мерный (вектор) массив со случайными целыми значениями 
np.random.randint(-10, 10, size=10)

array([ 3,  2,  0,  6,  2,  6,  0, -3,  5, -6])

In [13]:
# 2-мерный (матрица) массив со случайными целыми значениями 
np.random.randint(10, 100, size=(3, 5))

array([[14, 78, 26, 88, 30],
       [86, 88, 37, 17, 28],
       [34, 26, 10, 39, 78]])

In [16]:
# 3-мерный массив (тензор 3 ранга) со случайными целыми значениями
np.random.randint(10, 100, size=(3, 3, 5))

array([[[69, 13, 63, 30, 84],
        [67, 62, 86, 82, 36],
        [20, 83, 23, 73, 85]],

       [[28, 24, 34, 44, 80],
        [30, 69, 94, 85, 75],
        [69, 96, 33, 31, 38]],

       [[27, 66, 47, 15, 63],
        [94, 11, 17, 75, 41],
        [94, 20, 14, 23, 37]]])

In [24]:
# 1-мерный массив со случайными вещественными значениями
# из нормального (гауссова) распределения
# Медиана = 0, станд.отклонение = 1
np.random.randn(5)

array([ 0.00149797, -0.06550009, -0.51642469,  0.01529437,  0.82541134])

In [23]:
# 2-мерный массив со случайными вещественными значениями
# из нормального (гауссова) распределения
# Медиана = 0, станд.отклонение = 1
np.random.randn(3, 4)

array([[ 0.25255072,  1.45714552, -0.93960234, -0.70543426],
       [-0.72998982,  0.16852382, -1.10940964, -0.22507386],
       [-0.36018063,  0.74215427, -1.02007515,  0.85759922]])

In [25]:
# 2-мерный массив со случайными вещественными значениями
# из нормального (гауссова) распределения
# Медиана = 1, станд.отклонение = 2
np.random.normal(1,2,(3,3))

array([[0.06052667, 3.78007055, 0.74036561],
       [0.86348227, 1.265447  , 0.89286425],
       [3.26574182, 3.14314652, 0.14634423]])

- Атрибуты

In [29]:
arr_2 = np.random.randint(0,10, (3,5))
arr_2

array([[4, 2, 8, 8, 0],
       [0, 8, 0, 3, 1],
       [9, 2, 4, 7, 0]])

In [30]:
# формa
arr_2.shape

(3, 5)

In [31]:
# Общее количество значений
arr_2.size

15

In [32]:
# Мерность массива (количество измерений/осей)
arr_2.ndim

2

In [33]:
# Занимаемый объем памяти
arr_2.nbytes

60

In [34]:
# тип данных, хранящихся в массиве
arr_2.dtype 

dtype('int32')

- Методы

In [39]:
arr_2 = np.random.randint(0,10, (3,5))
arr_2

array([[7, 3, 3, 6, 5],
       [8, 0, 5, 7, 9],
       [9, 1, 2, 6, 8]])

In [40]:
# сортировка по столбцам
arr_2.sort(axis=0)
arr_2

array([[7, 0, 2, 6, 5],
       [8, 1, 3, 6, 8],
       [9, 3, 5, 7, 9]])

In [43]:
# сортировка по строкам
arr_2.sort(axis=1)
arr_2

array([[0, 2, 5, 6, 7],
       [1, 3, 6, 8, 8],
       [3, 5, 7, 9, 9]])

In [45]:
# реверс сортированных значений по строкам
arr_2.sort(axis=1)
arr_2[:,::-1]

array([[7, 6, 5, 2, 0],
       [8, 8, 6, 3, 1],
       [9, 9, 7, 5, 3]])

In [46]:
arr_2.flatten()

array([0, 2, 5, 6, 7, 1, 3, 6, 8, 8, 3, 5, 7, 9, 9])

In [47]:
arr_2.min(), arr_2.max(), arr_2.mean()

(0, 9, 5.266666666666667)

- Индексация

In [48]:
arr_2

array([[0, 2, 5, 6, 7],
       [1, 3, 6, 8, 8],
       [3, 5, 7, 9, 9]])

In [49]:
# Прямая индексация
arr_2[1]

array([1, 3, 6, 8, 8])

In [51]:
# Обратная индексация
arr_2[-1]

array([3, 5, 7, 9, 9])

In [52]:
# Извлечение значений элементов массива
# Стандартный питонящий синтаксис
arr_2[1][-1]


8

In [53]:
# Синтаксис NumPy
arr_2[1, -1]

8

- Срезы

In [54]:
arr_2

array([[0, 2, 5, 6, 7],
       [1, 3, 6, 8, 8],
       [3, 5, 7, 9, 9]])

In [55]:
arr_2[:2]

array([[0, 2, 5, 6, 7],
       [1, 3, 6, 8, 8]])

In [56]:
arr_2[:, :2]

array([[0, 2],
       [1, 3],
       [3, 5]])

In [57]:
arr_2[:, 1:4]

array([[2, 5, 6],
       [3, 6, 8],
       [5, 7, 9]])

In [60]:
arr_2[1:, 1:4]

array([[3, 6, 8],
       [5, 7, 9]])